### ISSUE TITLE
现场直播

### ISSUE THREAD

**Issue by misaka4e21** [AOSC-Dev/aoscc-2015#2]
也说不好能不能来，而且相信没条件但想来的同学还是不少的。
- 摄像头环节不必太多，以广播屏幕为主。
- 架设评论区，可使用IRC代替。
- 可考虑向部分可信人员（不包括本御坂）提供ssh和/或vpn等远程访问机制。
  未完待续

**Comment by MingcongBai** [comment]
摄像头指单个录影呢还是类似 Telepathy 一样的视频通话（Google Hangouts 很明显……）

**Comment by misaka4e21** [comment]
本来想的是多会场视频会议。既然不可行，那视频通话也就没什么意义了。
至于现场录像实时串流，本御坂突然开脑洞想到webcam，不过涉及现场环境、（可能的）在场非与会人员隐私等问题，或许也不行。因此说不必太多。 @MingcongBai

**Comment by MingcongBai** [comment]
@YeXiaoxing
2015年5月16日 下午9:31于 "Sz Netarmy" notifications@github.com写道：

**Comment by jyhi** [comment]
建议图文直播而不是视频串流，这样难度和现场要求会小很多。

**Comment by m13253** [comment]
如果是视频串流，我可以提供技术支持。（因为有RTMP串流经验）

正好我在写一个直播用弹幕姬，说不定可以配合IRC做互动。（Update: https://github.com/m13253/live-danmaku-hime）

**Comment by MingcongBai** [comment]
就是不知道现场是否有硬件和网络条件去实现了……
2015年5月16日 下午9:37于 "Star Brilliant" notifications@github.com写道：

**Comment by m13253** [comment]
> 就是不知道现场是否有硬件和网络条件去实现了……

真不行花钱租 3G 是了。如果经费够的话。

另外是现场直播远程放，还是家里直播现场放？

**Comment by MingcongBai** [comment]
需要一名摄影。

**Comment by tianyuf** [comment]
现场的网络情况如何呀？

**Comment by MingcongBai** [comment]
^ @Xiaoxing

**Comment by Yexiaoxing** [comment]
​No information is available to offer..​

Regards,
Xiaoxing Ye

**Comment by MingcongBai** [comment]
^ @Yexiaoxing
